### ISSUE TITLE
Bring dev dependencies into alignment with flagship project

### ISSUE THREAD

**Issue by indiebrain** [powerhome/power-web-development-interview#97]
An original goal of this project was to provide a typical development tech stack used at Power to candidates during the interview process.

Power's flagship project used the percona image for its database, but this has changed - it now uses the MySQL org's image. Furthermore, the flagship image is using a newer version of MySQL than this project. 

https://github.com/powerhome/nitro-web/blob/4e1fc00d07224812a917edba3d7001087c29b0ad/docker-compose.yml#L57

MySQL is just one example, but the purpose of this issue is to bring this project back into alignment with the nitro-web stack.

**Comment by xjunior** [comment]
@indiebrain I'm uncertain if it is possible to use the org's MySQL image in this project as it's used publicly, unless we publish the image to the docker hub.

/cc @benlangfeld

**Comment by indiebrain** [comment]
@xjunior nitro-web uses a publicly available image for its MySQL dependency:

```
docker.io/mysql/mysql-server:8.0.32
```

https://hub.docker.com/layers/mysql/mysql-server/8.0.32/images/sha256-b966c2c0c643c5c35a21e03fa0e49d5f8bf1177d39b35aba86cb12715fd824da?context=explore
